### ISSUE TITLE
TV-Spielfilm

### ISSUE THREAD

**Issue by etofi** [dlueth/easyepg.minimal#3] opened 2020-10-25 08:05 UTC
Unfortunately the creation of the XMLTV file from the source TV-Spielfim does not work anymore since tonight.

**Comment by dlueth** [comment] 2020-10-25 17:37
@etofi Is this docker/container related or a soon-to-be-fixed bug in easyepg itself?

**Comment by etofi** [comment] 2020-10-25 18:39
Looks to me like a special bug in the TV-Spielfim script. Enclosed the log [Log.txt](https://github.com/dlueth/easyepg.minimal/files/5435650/Log.txt).
When I run the Docker Container with the option "run" the container crashes and restarts itself.
The zattoo script alone works without problems.

**Comment by dlueth** [comment] 2020-10-25 19:39
OK, so this seems to be easyepg-related which is not my project, I just provide this Container to be able to run it via docker. Docker restarting when something crashes is just normal and expected behaviour ;) @etofi I'll see if I can get any info for you

**Comment by dlueth** [comment] 2020-10-25 19:46
Contacted easy4me via kodinerds about this issue @etofi

**Comment by sunsettrack4** [comment] 2020-10-25 21:49
Fixed: https://github.com/sunsettrack4/easyepg/commit/e438fe2bce411d871f8a2848e2e335d68eb215d4

**Comment by dlueth** [comment] 2020-10-26 04:58
Thx @sunsettrack4 - closing this issue. @etofi pls update your installation of easyepg and you should be fine ;)

**Closed as completed by dlueth** 2020-10-26 04:58 UTC

**Comment by etofi** [comment] 2020-10-26 06:24
Thanks
